### ISSUE TITLE
baidu 网盘链接过期

### ISSUE THREAD

**Issue by chenjiachengzzz** [BITszwang/CTNet#1]
您好，您提供的百度网盘链接失效了，可否再次分享。

**Comment by BITszwang** [comment]
谢谢提醒！我已经上传到OneDrive网盘, 你可以从这个[链接](https://dhldhl-my.sharepoint.com/:f:/g/personal/kckclcto_yiciedu_com/Eko38C-i_RNJll5V43t2fVMB8EszYs6L1hmIu8Vfyy0eJA?e=cRiViv)下载，密码为912V。如果有问题，随时欢迎邮件交流。再次感谢！

**Comment by chenjiachengzzz** [comment]
> 谢谢提醒！我已经上传到OneDrive网盘, 你可以从这个[链接](https://dhldhl-my.sharepoint.com/:f:/g/personal/kckclcto_yiciedu_com/Eko38C-i_RNJll5V43t2fVMB8EszYs6L1hmIu8Vfyy0eJA?e=cRiViv)下载，密码为912V。如果有问题，随时欢迎邮件交流。再次感谢！

非常感谢您的及时回复！

**Comment by JusticeLin** [comment]
> > 谢谢提醒！我已经上传到OneDrive网盘, 你可以从这个[链接](https://dhldhl-my.sharepoint.com/:f:/g/personal/kckclcto_yiciedu_com/Eko38C-i_RNJll5V43t2fVMB8EszYs6L1hmIu8Vfyy0eJA?e=cRiViv)下载，密码为912V。如果有问题，随时欢迎邮件交流。再次感谢！
> 
> 非常感谢您的及时回复！

里面缺少了两张图片，需要注意一下，分别是train/HR/intersection49及val/HR/mediumresidential81（我这边解压总会出现错误，不知道你那里会不会）

**Comment by BITszwang** [comment]
> > > 谢谢提醒！我已经上传到OneDrive网盘, 你可以从这个[链接](https://dhldhl-my.sharepoint.com/:f:/g/personal/kckclcto_yiciedu_com/Eko38C-i_RNJll5V43t2fVMB8EszYs6L1hmIu8Vfyy0eJA?e=cRiViv)下载，密码为912V。如果有问题，随时欢迎邮件交流。再次感谢！
> > 
> > 
> > 非常感谢您的及时回复！
> 
> 里面缺少了两张图片，需要注意一下，分别是train/HR/intersection49及val/HR/mediumresidential81（我这边解压总会出现错误，不知道你那里会不会）

谢谢提醒，我这边检查一下，回复你。

**Comment by chenjiachengzzz** [comment]
> > > 谢谢提醒！我已经上传到OneDrive网盘, 你可以从这个[链接](https://dhldhl-my.sharepoint.com/:f:/g/personal/kckclcto_yiciedu_com/Eko38C-i_RNJll5V43t2fVMB8EszYs6L1hmIu8Vfyy0eJA?e=cRiViv)下载，密码为912V。如果有问题，随时欢迎邮件交流。再次感谢！
> > 
> > 
> > 非常感谢您的及时回复！
> 
> 里面缺少了两张图片，需要注意一下，分别是train/HR/intersection49及val/HR/mediumresidential81（我这边解压总会出现错误，不知道你那里会不会）
俺也是，我是把原来数据集里的相应图片放进去了

**Comment by BITszwang** [comment]
> > > 谢谢提醒！我已经上传到OneDrive网盘, 你可以从这个[链接](https://dhldhl-my.sharepoint.com/:f:/g/personal/kckclcto_yiciedu_com/Eko38C-i_RNJll5V43t2fVMB8EszYs6L1hmIu8Vfyy0eJA?e=cRiViv)下载，密码为912V。如果有问题，随时欢迎邮件交流。再次感谢！
> > 
> > 
> > 非常感谢您的及时回复！
> 
> 里面缺少了两张图片，需要注意一下，分别是train/HR/intersection49及val/HR/mediumresidential81（我这边解压总会出现错误，不知道你那里会不会）

@JusticeLin @chenjiachengzzz 感谢提醒！我已经重新更新OneDrive网盘内容。给你们实验造成不便，十分抱歉！Github回复不及时，如果后续有问题可以给我发送邮件shunzhouwang@bit.edu.cn，可以对这个课题做进一步交流。再次感谢！
