### ISSUE TITLE
读取不了数据集

### ISSUE THREAD

**Issue by JusticeLin** [BITszwang/CTNet#2]
PS F:\Broswer_Download\CTNet-main\CTNet-main\codes> python demo_train_ctnet.py --model=CTNET --dataset=UCMerced --scale=4 --patch_size=192 --ext=img --save=CTNETx4_UCMerced
Read data from image files
Read data from image files
0
Traceback (most recent call last):
  File "demo_train_ctnet.py", line 12, in <module>
    dataloaders = data.create_dataloaders(args)
  File "F:\Broswer_Download\CTNet-main\CTNet-main\codes\data\__init__.py", line 30, in create_dataloaders
    shuffle=True, num_workers=6),  # args.n_threads
  File "C:\ProgramData\Anaconda3\envs\py37\lib\site-packages\torch\utils\data\dataloader.py", line 262, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore
  File "C:\ProgramData\Anaconda3\envs\py37\lib\site-packages\torch\utils\data\sampler.py", line 104, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0
无法读取数据集，请问是怎么回事呢，我的数据集是分为train和test，分别放1050张图片

**Comment by JusticeLin** [comment]
打印出来的数据长度为0

**Comment by chenjiachengzzz** [comment]
> 打印出来的数据长度为0

哥们，你数据集哪里下的qaq

**Comment by BITszwang** [comment]
感谢关注！我感觉是你的数据集路径没有进行设置。数据集路径需要根据你下载的情况在[data/init.py](https://github.com/BITszwang/CTNet/blob/main/codes/data/__init__.py)中设置。由于之前百度网盘链接失效，我重新提供了OneDrive网盘的数据集[下载链接](https://dhldhl-my.sharepoint.com/:f:/g/personal/kckclcto_yiciedu_com/Eko38C-i_RNJll5V43t2fVMB8EszYs6L1hmIu8Vfyy0eJA?e=cRiViv)，密码为“912V”。你可重新下载数据集，并按照readme.md的指示来。如果有还有疑问，可以随时邮件联络我。再次感谢！

**Comment by JusticeLin** [comment]
> > 打印出来的数据长度为0
> 
> 哥们，你数据集哪里下的qaq

我是自己百度搜的，不过现在作者又上传了

**Comment by JusticeLin** [comment]
> 感谢关注！我感觉是你的数据集路径没有进行设置。数据集路径需要根据你下载的情况在[data/init.py](https://github.com/BITszwang/CTNet/blob/main/codes/data/__init__.py)中设置。由于之前百度网盘链接失效，我重新提供了OneDrive网盘的数据集[下载链接](https://dhldhl-my.sharepoint.com/:f:/g/personal/kckclcto_yiciedu_com/Eko38C-i_RNJll5V43t2fVMB8EszYs6L1hmIu8Vfyy0eJA?e=cRiViv)，密码为“912V”。你可重新下载数据集，并按照readme.md的指示来。如果有还有疑问，可以随时邮件联络我。再次感谢！

**Comment by JusticeLin** [comment]
>

**Comment by JusticeLin** [comment]
> 感谢关注！我感觉是你的数据集路径没有进行设置。数据集路径需要根据你下载的情况在[data/init.py](https://github.com/BITszwang/CTNet/blob/main/codes/data/__init__.py)中设置。由于之前百度网盘链接失效，我重新提供了OneDrive网盘的数据集[下载链接](https://dhldhl-my.sharepoint.com/:f:/g/personal/kckclcto_yiciedu_com/Eko38C-i_RNJll5V43t2fVMB8EszYs6L1hmIu8Vfyy0eJA?e=cRiViv)，密码为“912V”。你可重新下载数据集，并按照readme.md的指示来。如果有还有疑问，可以随时邮件联络我。再次感谢！

感谢您的答复！我下载您的数据集再进行尝试。
