### ISSUE TITLE
About LR image 

### ISSUE THREAD

**Issue by oldcatl** [BITszwang/CTNet#4]
Hi, regarding your dataset part, I would like to ask how you got the LR image based on the HR image.

**Comment by BITszwang** [comment]
> Hi, regarding your dataset part, I would like to ask how you got the LR image based on the HR image.

Thanks for your attention. We use the bicubic interpolation operation to generate the LR images following HSENet. The dataset generation code is also provided in /codes/data_scripts/.

**Comment by oldcatl** [comment]
Thank you for your reply. I have no questions now.
